"""add is_deleted to assignments

Revision ID: 19895d03d6f3
Revises: 7ed34ff3615e
Create Date: 2026-06-30 19:10:49.262827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19895d03d6f3'
down_revision: Union[str, Sequence[str], None] = '7ed34ff3615e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
