"""add is_deleted to assignments

Revision ID: 1bfe6392c5b4
Revises: 94a8e56f27c8
Create Date: 2026-06-30 19:20:42.411066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfe6392c5b4'
down_revision: Union[str, Sequence[str], None] = '94a8e56f27c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'is_deleted')
    # ### end Alembic commands ###
