"""add is_deleted to assignments

Revision ID: 35e53b54f0ba
Revises: 19895d03d6f3
Create Date: 2026-06-30 19:16:04.674008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e53b54f0ba'
down_revision: Union[str, Sequence[str], None] = '19895d03d6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'is_deleted')
    # ### end Alembic commands ###
