"""add is_deleted to assignments

Revision ID: 7ed34ff3615e
Revises: fbbdc06a2f75
Create Date: 2026-06-30 19:02:40.605442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed34ff3615e'
down_revision: Union[str, Sequence[str], None] = 'fbbdc06a2f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'is_deleted')
    # ### end Alembic commands ###
