"""add is_deleted to assignments

Revision ID: fbbdc06a2f75
Revises: 
Create Date: 2026-06-30 18:58:21.396298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbbdc06a2f75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_structures_id'), table_name='structures')
    op.drop_table('structures')
    op.drop_index(op.f('ix_bones_id'), table_name='bones')
    op.drop_table('bones')
    op.drop_index(op.f('ix_anatomical_areas_id'), table_name='anatomical_areas')
    op.drop_table('anatomical_areas')
    op.drop_index(op.f('ix_joints_id'), table_name='joints')
    op.drop_table('joints')
    op.add_column('templates', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'is_deleted')
    op.create_table('joints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name_ru', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name_lat', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bone_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('correct_connections', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('description_ru', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['anatomical_areas.id'], name=op.f('joints_area_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('joints_pkey'))
    )
    op.create_index(op.f('ix_joints_id'), 'joints', ['id'], unique=False)
    op.create_table('anatomical_areas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_ru', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name_lat', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('anatomical_areas_pkey'))
    )
    op.create_index(op.f('ix_anatomical_areas_id'), 'anatomical_areas', ['id'], unique=False)
    op.create_table('bones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name_ru', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name_lat', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('landmarks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['anatomical_areas.id'], name=op.f('bones_area_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bones_pkey'))
    )
    op.create_index(op.f('ix_bones_id'), 'bones', ['id'], unique=False)
    op.create_table('structures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name_ru', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name_lat', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bone_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('correct_connections', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('description_ru', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['anatomical_areas.id'], name=op.f('structures_area_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('structures_pkey'))
    )
    op.create_index(op.f('ix_structures_id'), 'structures', ['id'], unique=False)
    # ### end Alembic commands ###
